### ISSUE TITLE
Latest Data Page changes (DataViewer v0.9.8)

### ISSUE THREAD

**Issue by BrandonAQ** [MazamaScience/AirSensorDataViewer#16]
Latest Data Page	
- [x]    Replace “Latest” with “Last 48-hr Data”
- [x]  Display only last 48 hours of data
- [ ]  When zooming in on one plot, other two plots should zoom as well.

**Comment by jonathancallahan** [comment]
I'm going to replace this last suggestion with a new issue -- #32
