### ISSUE TITLE
About Page (DataViewer v0.9.8)

### ISSUE THREAD

**Issue by BrandonAQ** [MazamaScience/AirSensorDataViewer#17]
About Page requested updates: 
- [x] Update text and add link to paper -  https://doi.org/10.1016/j.envsoft.2020.104832 
- [x] Replace references to AirShiny with DataViewer
- [ ] Add color scale with concentration breaks information to the About page

**Comment by jonathancallahan** [comment]
SCAQMD should provide a PNG file with the appropriate color scale information.

**Comment by hansmrtn** [comment]
This has been implemented in static `html` to avoid scaling/other browser issues and is no longer applicable.
