### ISSUE TITLE
Historical Data Page - Overview Tab - Slider updates (DataViewer v0.9.8)

### ISSUE THREAD

**Issue by BrandonAQ** [MazamaScience/AirSensorDataViewer#21]
Historical Data Page - Overview Tab - Slider updates

Slider should not overlay over bar chart
Options: 
1.	Option to move this to be the axis of the BarChart to create a combined axis overlapping
2.	Option 2 move slider to be right above barchart

**Comment by hansmrtn** [comment]
This bug has been resolved
