### ISSUE TITLE
Historical Data Page - Tabular Data Tab (DataViewer v0.9.8)

### ISSUE THREAD

**Issue by BrandonAQ** [MazamaScience/AirSensorDataViewer#24]
Historical Data Page - Tabular Data Tab

- [x] All data in columns should be centered
- [x] Top bar Text changes
    - “Sensor” change to “Sensor Name”
    - “Sensor.Type” change to “Sensor Model” and text “PA-II (PurpleAir)”
- [x] Include option to download tabular data shown on this tab 
- [x] Remove search box feature – not needed

**Comment by hansmrtn** [comment]
The download button exists on the side-panel. Should it also exist on the page itself?

**Comment by jonathancallahan** [comment]
A Download button already exists underneath the selection elements on the left.
