### ISSUE TITLE
Historical Data Page - Daily Patterns Tab (DataViewer v0.9.8)

### ISSUE THREAD

**Issue by BrandonAQ** [MazamaScience/AirSensorDataViewer#25]
Historical Data Page - Daily Patterns Tab

- [x] Wind Rose plot not displaying on DataViewer for recent dates 
- [x] For Bar Chart x-axis label, change “Time of Day (local)” to “Hour of Day (local)”

**Comment by hansmrtn** [comment]
The NOAA data required for the wind rose plot appears to have a day or two lag for most locations - which unfortunately is out of our hands.
