### ISSUE TITLE
Historical Data Page - Community Timelapse tab (DataViewer v0.9.8)

### ISSUE THREAD

**Issue by BrandonAQ** [MazamaScience/AirSensorDataViewer#27]
Historical Data Page - Community Timelapse tab

- [x] Reduce text size of PM2.5
- [x] Add units to color bar 
- [x] Date Range needs to be single end date selection to see prior 7 days
- [x] deploy to Mazama server

**Comment by jonathancallahan** [comment]
This is work that will happen over in AQ-SPEC-sensor-data-ingest-v1 with the complete refactoring of the video creation script.
