### ISSUE TITLE
discrepancies between dates selected and dates displayed in bar chart

### ISSUE THREAD

**Issue by acollier-oxandale** [MazamaScience/AirSensorDataViewer#30]
In the three examples below, where dates from November 2019 are selected there appears to be a discrepancy between selected dates and the data displayed in the bar chart on the Overview tab. (let me know if these errors are not reproducible) 

Example 1: (Alhambra, SCAP_03, 2019-11-18 - 2019-11-21)
![image](https://user-images.githubusercontent.com/48835544/93927333-923a2200-fccd-11ea-8083-4729577119bb.png)

Example 2: (Alhambra, SCAP_50, 2019-11-15 - 2019-11-21)
![image](https://user-images.githubusercontent.com/48835544/93927437-b85fc200-fccd-11ea-942c-b04e5867ce55.png)

Example 3: (All, SCUV_06, 2019-11-07 - 2019-11-21 
![image](https://user-images.githubusercontent.com/48835544/93927616-feb52100-fccd-11ea-897c-aae4433c5157.png)

**Comment by hansmrtn** [comment]
This has been resolved in the latets AirSensor side of things.
