### ISSUE TITLE
Tabular data - edit 1

### ISSUE THREAD

**Issue by acollier-oxandale** [MazamaScience/AirSensorDataViewer#42]
Rather than displaying every minute and staggered Ch A/Ch B data, could A and B be matched to the nearest 2-minute? This will be much easier for users to work with if they download the data.

(Version: 1.0.1)

**Comment by jonathancallahan** [comment]
Can you provide an example showing this?

**Comment by acollier-oxandale** [comment]
I am pretty sure this was implemented in the previous version of the DataViewer using rounding, I've added a screenshot below

![image](https://user-images.githubusercontent.com/48835544/97641598-7cbcc400-1a00-11eb-9c3f-6022f555b977.png)

**Comment by jonathancallahan** [comment]
I still don't understand the request. I don't see any "staggered" values here.

**Comment by hansmrtn** [comment]
I understand what is being said here and will address it in the next update! 

This has to do with the way the data is being displayed in the tabular data section. Right now what is being displayed is the unaltered PurpleAir data, with its natural sensor staggered reporting.
